defmodule :"Elixir.Fuelex.Repo.Migrations.Add ships table" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ships, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:mass, :bigint, null: false)
    end
  end

  def down do
    drop(table(:ships))
  end
end
