defmodule :"Elixir.Fuelex.Repo.Migrations.Init db" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:gravities, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:planet, :text, null: false)
      add(:constant, :float, null: false)
    end

    create table(:constants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:type, :text)
      add(:residual, :bigint, null: false)
      add(:constant, :float, null: false)
    end
  end

  def down do
    drop(table(:constants))

    drop(table(:gravities))
  end
end
